// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Report struct {
	ID        uuid.UUID
	Title     string
	CreatedBy string
	CreatedAt time.Time
}

type ReportCell struct {
	ID       uuid.UUID
	ReportID uuid.UUID
	Position int32
	Kind     string
	Text     *string
	ValueID  uuid.NullUUID
	Label    *string
}

type ReportCellSumInput struct {
	SumCellID uuid.UUID
	ValueID   uuid.UUID
	Sign      int16
}

type SourceValue struct {
	ID        uuid.UUID
	Key       string
	Label     string
	Amount    decimal.Decimal
	Unit      string
	Period    string
	Version   int32
	UpdatedAt time.Time
	UpdatedBy string
}

type User struct {
	ID          string
	DisplayName string
	CreatedAt   time.Time
}

type ValueChange struct {
	ID        int64
	ValueID   uuid.UUID
	OldAmount decimal.Decimal
	NewAmount decimal.Decimal
	Version   int32
	Reason    string
	ChangedBy string
	ChangedAt time.Time
}
