// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const listReportValueIDs = `-- name: ListReportValueIDs :many
SELECT c.value_id::uuid AS value_id
FROM report_cells c
WHERE c.report_id = $1 AND c.value_id IS NOT NULL
UNION
SELECT i.value_id
FROM report_cell_sum_inputs i
JOIN report_cells c ON c.id = i.sum_cell_id
WHERE c.report_id = $1
ORDER BY value_id
`

// The distinct values a report uses, through value_ref cells or sum inputs.
func (q *Queries) ListReportValueIDs(ctx context.Context, reportID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listReportValueIDs, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var value_id uuid.UUID
		if err := rows.Scan(&value_id); err != nil {
			return nil, err
		}
		items = append(items, value_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, title, created_by, created_at
FROM reports
ORDER BY created_at, id
`

func (q *Queries) ListReports(ctx context.Context) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
