// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: values.sql

package store

import (
	"context"
)

const listValues = `-- name: ListValues :many
SELECT id, key, label, amount, unit, period, version, updated_at, updated_by
FROM source_values
WHERE $1::text IS NULL OR period = $1::text
ORDER BY key
`

// Values in key order. A null period returns every period.
func (q *Queries) ListValues(ctx context.Context, period *string) ([]SourceValue, error) {
	rows, err := q.db.Query(ctx, listValues, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceValue{}
	for rows.Next() {
		var i SourceValue
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Amount,
			&i.Unit,
			&i.Period,
			&i.Version,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
